__Group Member Names:__ Ashton Hansen, Zach Barret


---

# Homework 2
__Guidelines:__ 
* Please write the names of all group members to the __"Group Member Names:"__ line above. 
* For the questions that require verbal answers, please answer them in their respective answer cells. 
* For the questions that require code, if your code doesn't work, please include a comment describing your algorithm (if code works well, no explanation is needed). 
* The question 1 is worth 1 point, question 5 is worth 3 points, and the other questions worth 2 points each. (Total: 10)
* This homework is due on __Mar. 3, 2021, 5:30 pm.__ You need to upload your completed homework assignment to Sakai as a Jupyter Notebook file (.ipynb) until that time.
---

In [10]:
import numpy as np         # Run this line at the beginning of your program as some packages will be needed.

---

## Question 1:

Write a function that calculates the future value of a current investment as follows.
* The function will have three arguments: pv, r, t 
* pv represents the current investment amount, r represents the yearly rate of return, t represents the investment term in years.
* The function should output the future value of the investment.
* You may assume annual compounding (i.e., Present value * $(1+r)^{t}$ = Future value).

The final function should look like: future_val(pv, r, t), where numbers will be in place of pv, r, t 

(e.g., after defining the function, running the following in a different cell, for example, should produce the appropriate output: >>> future_val(1000, 0.05, 10)). 

In [6]:
def future_val(pv, r, t):
    val = round(pv * (1 + r)**t, 2)
    return val
future_val(1000, 0.05, 10)

1628.89

---

## Question 2:

Write a program that calculates the internet bill of a customer, as follows:
* The program will first ask how many gigabytes (GB) of data customer used.
* Second, the program will ask how much is the per gigabyte rate.
* Third, the program will ask how many years has this person been a customer of the company. 
    * If the gigabytes used is greater than 100, then the customer will pay base rate for the first 100 GB, and pay __triple__ of that rate for the __extra__ gigabytes.
    * Furthermore, if the person has been a customer of the company for more than 2 years, then the person will also receive loyalty discount and the final total bill will be reduced by __20%__ (i.e. x0.8).
    
Finally, the program should print the internet bill amount of customer.

In [ ]:
gb = float(input("How many GB of data were used?"))
rate = float(input("What is the per GB rate?"))
years = float(input("How many years have you been a customer?"))

if gb > 100.0:
    bill = (100.0 * rate) + ((gb - 100.0) * (rate * 30.))
else:
        bill = gb*rate
if years > 2.0:
    bill = bill * 0.8
print("Internet bill:", bill)

## Question 3:

Write a program that achieves the following:
* The program will start with printing the square of 1, and will keep going on printing squares of 2, 3, 4, 5... . This procedure of loop should be automatic and should not require any manual inputting of a list of numbers etc.
* In other words, in each iteration, the program will print out the square of the respective number, such as 1, 4, 9, 16, 25...
* The program will stop once the square of a number exceeds 200.

To give an idea, the output should broadly look like (for brevity, "..." below represents the numbers in between):

1

4

...    

196

225


In [8]:
x = 0
out = 0
while out < 200:
    x += 1
    out = x**2
    print(out)

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225


---

## Question 4:

Consider the following string variable, which consists of a quote by Leonardo Da Vinci, 

s_var = "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things."

Define this string variable.

Write a code that first splits this string variable into individual words, and then constructs a new list variable that consists of these words. Next, your code should count the words in this list that has more than 5 characters. Finally, your code should print out the number of words with more than 5 characters in this string variable.

In [ ]:
s_var = "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things."


---

## __Question 5:__ 

a) Generate a NumPy array with 25 random integers between -50 and 50, inclusive. Then, reshape this array into a 5x5 matrix. Let's call this matrix M.

In [40]:
q5_array = np.random.randint(-50, 50, 25)
q5_matrix = np.matrix(q5_array).reshape(5,5)
print(q5_matrix)

[[ 12  10 -42  46 -45]
 [-37  33 -46  41  -3]
 [ -5 -41  -8 -20  16]
 [ -7 -39  40 -50 -27]
 [ 28 -14 -49 -44 -32]]


b) Calculate the mean, median, standard deviation, minimum, and maximum of the numbers in the matrix M.

In [41]:
average = np.mean(q5_matrix)
stdev = round(np.std(q5_matrix), 4)
minimum = np.min(q5_matrix)
maximum = np.max(q5_matrix)
print("Mean:", average, "St Dev:", stdev, "Min:", minimum, "Max:", maximum)

Mean: -11.32 St Dev: 31.2253 Min: -50 Max: 46


c) Multiply the matrix with itself. Also calculate the dot product of matrix M with itself. Are they different? Why? (A one or two sentence explanatory comment would suffice.)

In [39]:
print(q5_matrix * q5_matrix)
print(q5_matrix.dot(q5_matrix))

[[ 1641  -842 -2882  2293  2257]
 [ 1581  3103 -2931  1142  1890]
 [ -844    -9  1299  1117   881]
 [ -870 -2163  2211  2579  1521]
 [-2063  1271   242   403  1230]]
[[ 1641  -842 -2882  2293  2257]
 [ 1581  3103 -2931  1142  1890]
 [ -844    -9  1299  1117   881]
 [ -870 -2163  2211  2579  1521]
 [-2063  1271   242   403  1230]]


The resulting matrices are the same. When NumPy matrices are multiplied together, the dot product is calculated instead of the elementwise products.

---